server:
  port: 8080
  tomcat:
    connection-timeout: 5000

management:
  endpoints:
    web:
      exposure:
        include: 'health'

spring:
  application:
    name: backoffce-api
  profiles:
    active: local
  jpa:
    open-in-view: false
  h2:
    console:
      enabled: false
  graphql:
    graphiql:
      enabled: true