spring:
  config:
    activate:
      on-profile: local
  jpa:
    hibernate:
      ddl-auto: create-drop
      show-sql: true
      generate-ddl: true
      datasource:
        url: jdbc:h2:mem:test;MODE=MySQL
        username: sa
    sql:
      init:
        mode: always
      output:
        ansi:
          enabled: always
      h2:
        console:
          enabled: true

logging:
  level:
    root: INFO
    org:
      springframework:
        transaction: DEBUG
        orm:
          jpa: DEBUG
        cache: TRACE
