spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sketch-api?autoReconnect=true
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    generate-ddl: true

    properties:
      hibernate:
        show_sql: true
        format_sql: true
        defer-datasource-initialization: true

  sql:
    init:
      mode: always
#      data-locations: classpath:sql/schema.sql
      schema-locations: classpath:sql/data.sql


spring.main.allow-bean-definition-overriding: true

graphql:
  servlet:
    enabled: true
    mapping: /graphql
    corsEnabled: false
    cors:
      allowed-origins: http://localhost:8080
      allowed-methods: GET, HEAD, POST, PATCH
    exception-handlers-enabled: true
    context-setting: PER_REQUEST_WITH_INSTRUMENTATION
    async-mode-enabled: true
  tools:
    schema-location-pattern: "**/*.graphql"
    introspection-enabled: true
